# version: "3.9"

# services:
#   app-prod:
#     container_name: neko_server_${NODE_ENV}
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile
#     ports:
#       - "${APP_PORT}:${APP_PORT}"
#     volumes:
#       - .:/server
#     restart: always
#     environment:
#       NODE_ENV: ${NODE_ENV}
#       APP_PORT: ${APP_PORT}

version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: server_backend
    ports:
      - "4000:4000"
    volumes:
      - .:/server
  client:
    build:
      context: .
      dockerfile: ./server/client/docker/Dockerfile
    container_name: client_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./server/client:/app
      # - ./app/node_modules
    stdin_open: true
    tty: true
